### ISSUE TITLE
Support strict content security policy

### ISSUE THREAD

**Issue by markdumay** [markdumay/hugo-theme-hinode#95]
Bootstrap uses [embedded SVG icons](https://getbootstrap.com/docs/5.2/customize/overview/#csps-and-embedded-svgs) throughout the SCSS files. The strict content security policy of the theme refuses to load these embedded files, resulting in missing icons. See Bootstrap issue [#33134](https://github.com/twbs/bootstrap/issues/33134) for more details.

**Comment by momargoh** [comment]
Hi Mark, I'm trying to use your theme on a blog deployed on netlify, but none of the styles are loading. Checking the console log, there seems to be an issue with content security policy for script-src but I can't see any more detail than just `Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src").`

My blog is www.barefootbushwalk.blog and the repo is at https://github.com/momargoh/barefootbushwalk . Are you able to help me out with this because I think your theme looks great and would love to be able to use it!

**Comment by markdumay** [comment]
Hi Momar, great to hear you like the theme! I was able to recreate the problem and to provide a solution. I submitted two additional bug reports too. I created a fork of your repo [here](https://github.com/markdumay/barefootbushwalk). These are my observations and recommendations:

1. I reverted back to the original `netlify.toml` file, as your configuration seemed to have different indentation. I'm not sure how strict `toml` processing is, but I changed back to the original indentation anyways.
2. I added the required CSP items for `script-src`, `frame-src`, and `img-src`, some of them were not in sync with your `server.toml` (which contains the CSP configuration for local development).
3. I added the command `npm run prod` to the `package.json` file to start a local production server to reproduce the CSS errors.
4. I added a new file `layouts/partials/head/stylesheet.html` to provide a fix for the incorrect CSS purge in production.
5. The site has been deployed to Netlify on [bush.markdumay.org](https://bush.markdumay.org).

I'll submit a PR to your repo so you can integrate the fixes with your own repo if you wish. Be sure to change back the `baseURL` though, as I updated this to `bush.markdumay.org` for testing with Netlify.

**Comment by momargoh** [comment]
Thank you so much Mark, I can't believe how quickly you've fixed that up. I just merged your PR and fixed up the `baseURL` and everything is deployed already! Enjoy your coffees :)

**Comment by markdumay** [comment]
Fixed with #109
